accent = "#fee801"
cursor = "#fee801"
foreground = "#d8eef8"
background = "#00060e"
selection_foreground = "#00060e"
selection_background = "#071520"

color0 = "#00060e"
color1 = "#fee801"
color2 = "#39c4b6"
color3 = "#fee801"
color4 = "#54c1e6"
color5 = "#9a9f17"
color6 = "#54c1e6"
color7 = "#d8eef8"
color8 = "#071520"
color9 = "#fee801"
color10 = "#39c4b6"
color11 = "#fee801"
color12 = "#54c1e6"
color13 = "#9a9f17"
color14 = "#54c1e6"
color15 = "#ffffff"
