$activeBorderColor = rgba(fee801ee) rgba(54c1e6ee) 45deg
$inactiveBorderColor = rgba(9a9f17ff)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
